### ISSUE TITLE
Kubernetes setup

### ISSUE THREAD

**Issue by virus2016** [openreplay/documentation#10]
Hi there,

The kubernetes/helm setup is tightly coupled to nginx. We use kong as the alernative.

Could I suggest allowing users to disable the nginx resouces in the helm? Much like the other services such as Postgres, Minio etc?

**Comment by rjshrjndrn** [comment]
You can already do that in vars.yaml, nginx installation is conditional.

https://github.com/openreplay/openreplay/blob/7fc8fab4d7d40248f7a22ca076ea9d0d12179c6e/scripts/helmcharts/openreplay/Chart.yaml#L31

You can add

```
ingress-nginx:
  enabled: false
  controller:
     ingressClassResource:
         name: (your ingress name) 
     ingressClass: (your ingress name) 
```
